const constants = {
	ADD_REVIEW: "ADD_REVIEW",
	EDIT_REVIEW: "EDIT_REVIEW",
	ADD_STARS: "ADD_STARS",
	DELETE_REVIEW: "DELETE_REVIEW",
	ADD_REPLY: "ADD_REPLY",
	FETCH_DATA: "FETCH_DATA",
	TOGGLE_EDITING: "TOGGLE_EDITING",
	TOGGLE_REPLYING: "TOGGLE_REPLYING",
	FILTER_REVIEWS: "FILTER_REVIEWS"
};

export default constants;